import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LogoBar from "./components/logoBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html className="h-full w-full scroll-smooth" lang="en">
      <body
        className={
          geistSans.variable +
          " " +
          geistMono.variable +
          " h-full w-full min-h-screen bg-slate-50 antialiased selection:bg-blue-200 selection:text-slate-900"
        }
      >
        <div className="mx-auto max-w-6xl py-6 md:py-8 lg:py-10 px-5 sm:px-10 md:px-16 lg:px-10">
          <header className="mb-2">
            <LogoBar />
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}